.PHONY: all clean

LATEXMK:=latexmk
BIBTEX:=bibtex
TARGET:=projectDocument.pdf
MAINTEX:=$(subst pdf,tex,$(TARGET))

LATEXMKFLAGS=-pdf -pdflatex="pdflatex -interaction=nonstopmode" -use-make $<
LATEXCLFLAGS=-CA

all: $(TARGET)

%.bbl : %.aux
	$(BIBTEX) $<

$(TARGET) : $(MAINTEX)
	$(LATEXMK) $(LATEXMKFLAGS)

clean:
	$(LATEXMK) $(LATEXCLFLAGS)
